/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Color;
import javax.swing.JFrame;
import autentikasi.Login;
import com.mycompany.FantasyFittings.koneksiDB;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author Rafly Ivan Khalfani
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Main_Menu
     */
    

    
    public Dashboard() {
        initComponents();
        CountStatOutfitType();
        CountStatOutfitQTY();
        CountStatRented();
        CountStatAvailable();
        CountRevenue();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_sidebar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pn_logo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pn_user = new javax.swing.JPanel();
        dash_user = new javax.swing.JLabel();
        dash_username = new javax.swing.JLabel();
        pn_btnDashboard = new javax.swing.JPanel();
        pn_line = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pn_btnOutfit = new javax.swing.JPanel();
        pn_line1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pn_btnPenyewaan = new javax.swing.JPanel();
        pn_line2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pn_btnPelanggan = new javax.swing.JPanel();
        pn_line3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pn_btnPembayaran = new javax.swing.JPanel();
        pn_line4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        pn_body = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        StatKostum = new javax.swing.JPanel();
        StatKostumNumber = new javax.swing.JLabel();
        LabelStatKostumType = new javax.swing.JLabel();
        StatKostumTersedia = new javax.swing.JPanel();
        LabelKostumTersedia = new javax.swing.JLabel();
        StatAvailable = new javax.swing.JLabel();
        StatJumlahKostum = new javax.swing.JPanel();
        LabelKostumQTY = new javax.swing.JLabel();
        StatKostumQTY = new javax.swing.JLabel();
        StatKostumDipinjam = new javax.swing.JPanel();
        LabelStatKostum2 = new javax.swing.JLabel();
        KostumDipinjam = new javax.swing.JLabel();
        StatTotalPendapatan = new javax.swing.JPanel();
        LabelPendapatan = new javax.swing.JLabel();
        TotalPendapatan = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        Ikon = new javax.swing.JLabel();
        Catchphrase = new javax.swing.JLabel();
        Catchphrase2 = new javax.swing.JLabel();
        Catchphrase3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_sidebar.setPreferredSize(new java.awt.Dimension(200, 540));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pn_logo.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-name-2.png"))); // NOI18N

        javax.swing.GroupLayout pn_logoLayout = new javax.swing.GroupLayout(pn_logo);
        pn_logo.setLayout(pn_logoLayout);
        pn_logoLayout.setHorizontalGroup(
            pn_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_logoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap())
        );
        pn_logoLayout.setVerticalGroup(
            pn_logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_logoLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(14, 14, 14))
        );

        pn_user.setBackground(new java.awt.Color(255, 255, 255));
        pn_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_userMouseClicked(evt);
            }
        });

        dash_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dash_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N

        dash_username.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        dash_username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dash_username.setText("USERNAME");

        javax.swing.GroupLayout pn_userLayout = new javax.swing.GroupLayout(pn_user);
        pn_user.setLayout(pn_userLayout);
        pn_userLayout.setHorizontalGroup(
            pn_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dash_user, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dash_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_userLayout.setVerticalGroup(
            pn_userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_userLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dash_user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dash_username)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_btnDashboard.setBackground(new java.awt.Color(255, 255, 255));
        pn_btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_btnDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_btnDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_btnDashboardMouseExited(evt);
            }
        });

        pn_line.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_lineLayout = new javax.swing.GroupLayout(pn_line);
        pn_line.setLayout(pn_lineLayout);
        pn_lineLayout.setHorizontalGroup(
            pn_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        pn_lineLayout.setVerticalGroup(
            pn_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("Dashboard");

        javax.swing.GroupLayout pn_btnDashboardLayout = new javax.swing.GroupLayout(pn_btnDashboard);
        pn_btnDashboard.setLayout(pn_btnDashboardLayout);
        pn_btnDashboardLayout.setHorizontalGroup(
            pn_btnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_btnDashboardLayout.setVerticalGroup(
            pn_btnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_btnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_btnDashboardLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addComponent(pn_line, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_btnOutfit.setBackground(new java.awt.Color(255, 255, 255));
        pn_btnOutfit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_btnOutfitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_btnOutfitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_btnOutfitMouseExited(evt);
            }
        });

        pn_line1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line1Layout = new javax.swing.GroupLayout(pn_line1);
        pn_line1.setLayout(pn_line1Layout);
        pn_line1Layout.setHorizontalGroup(
            pn_line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        pn_line1Layout.setVerticalGroup(
            pn_line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kostum.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("Outfit");

        javax.swing.GroupLayout pn_btnOutfitLayout = new javax.swing.GroupLayout(pn_btnOutfit);
        pn_btnOutfit.setLayout(pn_btnOutfitLayout);
        pn_btnOutfitLayout.setHorizontalGroup(
            pn_btnOutfitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnOutfitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_btnOutfitLayout.setVerticalGroup(
            pn_btnOutfitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnOutfitLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_btnOutfitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_btnOutfitLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addComponent(pn_line1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_btnPenyewaan.setBackground(new java.awt.Color(255, 255, 255));
        pn_btnPenyewaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_btnPenyewaanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_btnPenyewaanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_btnPenyewaanMouseExited(evt);
            }
        });

        pn_line2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line2Layout = new javax.swing.GroupLayout(pn_line2);
        pn_line2.setLayout(pn_line2Layout);
        pn_line2Layout.setHorizontalGroup(
            pn_line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        pn_line2Layout.setVerticalGroup(
            pn_line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/penyewaan.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setText("Penyewaan");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pn_btnPenyewaanLayout = new javax.swing.GroupLayout(pn_btnPenyewaan);
        pn_btnPenyewaan.setLayout(pn_btnPenyewaanLayout);
        pn_btnPenyewaanLayout.setHorizontalGroup(
            pn_btnPenyewaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnPenyewaanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_line2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_btnPenyewaanLayout.setVerticalGroup(
            pn_btnPenyewaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnPenyewaanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_btnPenyewaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_btnPenyewaanLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addComponent(pn_line2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_btnPelanggan.setBackground(new java.awt.Color(255, 255, 255));
        pn_btnPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_btnPelangganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_btnPelangganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_btnPelangganMouseExited(evt);
            }
        });

        pn_line3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line3Layout = new javax.swing.GroupLayout(pn_line3);
        pn_line3.setLayout(pn_line3Layout);
        pn_line3Layout.setHorizontalGroup(
            pn_line3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        pn_line3Layout.setVerticalGroup(
            pn_line3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pelanggan.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setText("Pelanggan");

        javax.swing.GroupLayout pn_btnPelangganLayout = new javax.swing.GroupLayout(pn_btnPelanggan);
        pn_btnPelanggan.setLayout(pn_btnPelangganLayout);
        pn_btnPelangganLayout.setHorizontalGroup(
            pn_btnPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnPelangganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_line3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_btnPelangganLayout.setVerticalGroup(
            pn_btnPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnPelangganLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_btnPelangganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_btnPelangganLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addComponent(pn_line3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_btnPembayaran.setBackground(new java.awt.Color(255, 255, 255));
        pn_btnPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_btnPembayaranMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_btnPembayaranMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_btnPembayaranMouseExited(evt);
            }
        });

        pn_line4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_line4Layout = new javax.swing.GroupLayout(pn_line4);
        pn_line4.setLayout(pn_line4Layout);
        pn_line4Layout.setHorizontalGroup(
            pn_line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        pn_line4Layout.setVerticalGroup(
            pn_line4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pembayaran.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setText("Pembayaran");

        javax.swing.GroupLayout pn_btnPembayaranLayout = new javax.swing.GroupLayout(pn_btnPembayaran);
        pn_btnPembayaran.setLayout(pn_btnPembayaranLayout);
        pn_btnPembayaranLayout.setHorizontalGroup(
            pn_btnPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnPembayaranLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_line4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_btnPembayaranLayout.setVerticalGroup(
            pn_btnPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_btnPembayaranLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_btnPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_btnPembayaranLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel10))
                    .addComponent(pn_line4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Logout.setForeground(new java.awt.Color(0, 51, 204));
        Logout.setText("Logout");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(Logout)
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_btnDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_btnOutfit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_btnPenyewaan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_btnPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_btnPembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(pn_user, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pn_logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_btnOutfit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_btnPenyewaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_btnPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_btnPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                .addComponent(Logout)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout pn_sidebarLayout = new javax.swing.GroupLayout(pn_sidebar);
        pn_sidebar.setLayout(pn_sidebarLayout);
        pn_sidebarLayout.setHorizontalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_sidebarLayout.setVerticalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pn_sidebar, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel24.setText("Menu Dashboard");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashboard.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addGap(1047, 1047, 1047))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel25)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        StatKostum.setBackground(new java.awt.Color(0, 0, 0));
        StatKostum.setPreferredSize(new java.awt.Dimension(188, 160));

        StatKostumNumber.setBackground(new java.awt.Color(204, 204, 204));
        StatKostumNumber.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        StatKostumNumber.setForeground(new java.awt.Color(255, 255, 255));
        StatKostumNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        LabelStatKostumType.setBackground(new java.awt.Color(0, 0, 0));
        LabelStatKostumType.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelStatKostumType.setForeground(new java.awt.Color(255, 255, 255));
        LabelStatKostumType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelStatKostumType.setText("Cosplay Type");

        javax.swing.GroupLayout StatKostumLayout = new javax.swing.GroupLayout(StatKostum);
        StatKostum.setLayout(StatKostumLayout);
        StatKostumLayout.setHorizontalGroup(
            StatKostumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StatKostumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatKostumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(StatKostumNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelStatKostumType, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addContainerGap())
        );
        StatKostumLayout.setVerticalGroup(
            StatKostumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatKostumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelStatKostumType, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatKostumNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        StatKostumTersedia.setBackground(new java.awt.Color(0, 0, 0));
        StatKostumTersedia.setPreferredSize(new java.awt.Dimension(187, 160));

        LabelKostumTersedia.setBackground(new java.awt.Color(0, 0, 0));
        LabelKostumTersedia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelKostumTersedia.setForeground(new java.awt.Color(255, 255, 255));
        LabelKostumTersedia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelKostumTersedia.setText("Available");

        StatAvailable.setBackground(new java.awt.Color(0, 0, 0));
        StatAvailable.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        StatAvailable.setForeground(new java.awt.Color(255, 255, 255));
        StatAvailable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout StatKostumTersediaLayout = new javax.swing.GroupLayout(StatKostumTersedia);
        StatKostumTersedia.setLayout(StatKostumTersediaLayout);
        StatKostumTersediaLayout.setHorizontalGroup(
            StatKostumTersediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatKostumTersediaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatKostumTersediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelKostumTersedia, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(StatAvailable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        StatKostumTersediaLayout.setVerticalGroup(
            StatKostumTersediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatKostumTersediaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelKostumTersedia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        StatJumlahKostum.setBackground(new java.awt.Color(0, 0, 0));
        StatJumlahKostum.setPreferredSize(new java.awt.Dimension(188, 160));

        LabelKostumQTY.setBackground(new java.awt.Color(0, 0, 0));
        LabelKostumQTY.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelKostumQTY.setForeground(new java.awt.Color(255, 255, 255));
        LabelKostumQTY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelKostumQTY.setText("Cosplay QTY");

        StatKostumQTY.setBackground(new java.awt.Color(204, 204, 204));
        StatKostumQTY.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        StatKostumQTY.setForeground(new java.awt.Color(255, 255, 255));
        StatKostumQTY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout StatJumlahKostumLayout = new javax.swing.GroupLayout(StatJumlahKostum);
        StatJumlahKostum.setLayout(StatJumlahKostumLayout);
        StatJumlahKostumLayout.setHorizontalGroup(
            StatJumlahKostumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatJumlahKostumLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatJumlahKostumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StatJumlahKostumLayout.createSequentialGroup()
                        .addComponent(StatKostumQTY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(StatJumlahKostumLayout.createSequentialGroup()
                        .addComponent(LabelKostumQTY, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                        .addGap(4, 4, 4))))
        );
        StatJumlahKostumLayout.setVerticalGroup(
            StatJumlahKostumLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatJumlahKostumLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelKostumQTY, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatKostumQTY, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        StatKostumDipinjam.setBackground(new java.awt.Color(0, 0, 0));
        StatKostumDipinjam.setPreferredSize(new java.awt.Dimension(160, 160));

        LabelStatKostum2.setBackground(new java.awt.Color(0, 0, 0));
        LabelStatKostum2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelStatKostum2.setForeground(new java.awt.Color(255, 255, 255));
        LabelStatKostum2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelStatKostum2.setText("Rented");

        KostumDipinjam.setBackground(new java.awt.Color(0, 0, 0));
        KostumDipinjam.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        KostumDipinjam.setForeground(new java.awt.Color(255, 255, 255));
        KostumDipinjam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout StatKostumDipinjamLayout = new javax.swing.GroupLayout(StatKostumDipinjam);
        StatKostumDipinjam.setLayout(StatKostumDipinjamLayout);
        StatKostumDipinjamLayout.setHorizontalGroup(
            StatKostumDipinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatKostumDipinjamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatKostumDipinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KostumDipinjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelStatKostum2, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                .addContainerGap())
        );
        StatKostumDipinjamLayout.setVerticalGroup(
            StatKostumDipinjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatKostumDipinjamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelStatKostum2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KostumDipinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        StatTotalPendapatan.setBackground(new java.awt.Color(0, 0, 0));
        StatTotalPendapatan.setPreferredSize(new java.awt.Dimension(160, 160));

        LabelPendapatan.setBackground(new java.awt.Color(0, 0, 0));
        LabelPendapatan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelPendapatan.setForeground(new java.awt.Color(255, 255, 255));
        LabelPendapatan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelPendapatan.setText("This Month Revenue");

        TotalPendapatan.setBackground(new java.awt.Color(0, 0, 0));
        TotalPendapatan.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        TotalPendapatan.setForeground(new java.awt.Color(255, 255, 255));
        TotalPendapatan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout StatTotalPendapatanLayout = new javax.swing.GroupLayout(StatTotalPendapatan);
        StatTotalPendapatan.setLayout(StatTotalPendapatanLayout);
        StatTotalPendapatanLayout.setHorizontalGroup(
            StatTotalPendapatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StatTotalPendapatanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatTotalPendapatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TotalPendapatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LabelPendapatan, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))
                .addContainerGap())
        );
        StatTotalPendapatanLayout.setVerticalGroup(
            StatTotalPendapatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatTotalPendapatanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));

        Ikon.setBackground(new java.awt.Color(0, 0, 0));
        Ikon.setForeground(new java.awt.Color(255, 255, 255));
        Ikon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ikon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-name-2.png"))); // NOI18N
        Ikon.setOpaque(true);

        Catchphrase.setBackground(new java.awt.Color(0, 0, 0));
        Catchphrase.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        Catchphrase.setForeground(new java.awt.Color(255, 255, 255));
        Catchphrase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Catchphrase.setText("Tingkatkan petualanganmu, ");

        Catchphrase2.setBackground(new java.awt.Color(0, 0, 0));
        Catchphrase2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        Catchphrase2.setForeground(new java.awt.Color(255, 255, 255));
        Catchphrase2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Catchphrase2.setText("Berkreasi Tanpa Batas");

        Catchphrase3.setBackground(new java.awt.Color(0, 0, 0));
        Catchphrase3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        Catchphrase3.setForeground(new java.awt.Color(255, 255, 255));
        Catchphrase3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Catchphrase3.setText("Transformasi Tidak Terbatas");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ikon, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Catchphrase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Catchphrase3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                    .addComponent(Catchphrase2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(Catchphrase)
                .addGap(18, 18, 18)
                .addComponent(Catchphrase3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Catchphrase2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(Ikon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(StatKostum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(StatJumlahKostum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(StatKostumTersedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(StatKostumDipinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(StatTotalPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(StatKostumTersedia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(StatJumlahKostum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(StatKostum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(StatKostumDipinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StatTotalPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 154, Short.MAX_VALUE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout pn_bodyLayout = new javax.swing.GroupLayout(pn_body);
        pn_body.setLayout(pn_bodyLayout);
        pn_bodyLayout.setHorizontalGroup(
            pn_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_bodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(375, Short.MAX_VALUE))
        );
        pn_bodyLayout.setVerticalGroup(
            pn_bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_bodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(pn_body, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pn_btnDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnDashboardMouseEntered
        // TODO add your handling code here:
        pn_btnDashboard.setBackground(new Color(250, 250, 250));
        pn_line.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_pn_btnDashboardMouseEntered

    private void pn_btnDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnDashboardMouseExited
        // TODO add your handling code here:
        pn_btnDashboard.setBackground(new Color(255, 255, 255));
        pn_line.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_pn_btnDashboardMouseExited

    private void pn_btnOutfitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnOutfitMouseEntered
        // TODO add your handling code here:
        pn_btnOutfit.setBackground(new Color(250, 250, 250));
        pn_line1.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_pn_btnOutfitMouseEntered

    private void pn_btnOutfitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnOutfitMouseExited
        // TODO add your handling code here:
        pn_btnOutfit.setBackground(new Color(255, 255, 255));
        pn_line1.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_pn_btnOutfitMouseExited

    private void pn_btnPenyewaanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnPenyewaanMouseEntered
        // TODO add your handling code here:
        pn_btnPenyewaan.setBackground(new Color(250, 250, 250));
        pn_line2.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_pn_btnPenyewaanMouseEntered

    private void pn_btnPenyewaanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnPenyewaanMouseExited
        // TODO add your handling code here:
        pn_btnPenyewaan.setBackground(new Color(255, 255, 255));
        pn_line2.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_pn_btnPenyewaanMouseExited

    private void pn_btnPelangganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnPelangganMouseEntered
        // TODO add your handling code here:
        pn_btnPelanggan.setBackground(new Color(250, 250, 250));
        pn_line3.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_pn_btnPelangganMouseEntered

    private void pn_btnPelangganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnPelangganMouseExited
        // TODO add your handling code here:
        pn_btnPelanggan.setBackground(new Color(255, 255, 255));
        pn_line3.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_pn_btnPelangganMouseExited

    private void pn_btnPembayaranMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnPembayaranMouseEntered
        // TODO add your handling code here:
        pn_btnPembayaran.setBackground(new Color(250, 250, 250));
        pn_line4.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_pn_btnPembayaranMouseEntered

    private void pn_btnPembayaranMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnPembayaranMouseExited
        // TODO add your handling code here:
        pn_btnPembayaran.setBackground(new Color(255, 255, 255));
        pn_line4.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_pn_btnPembayaranMouseExited

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true); //Meredirect ke object Register
        this.dispose();
    }//GEN-LAST:event_LogoutMouseClicked

    private void pn_btnDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnDashboardMouseClicked
        new Dashboard().setVisible(true); //Meredirect ke object Dashboard
        this.dispose();
    }//GEN-LAST:event_pn_btnDashboardMouseClicked

    private void pn_btnOutfitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnOutfitMouseClicked
        new Outfit().setVisible(true); //Meredirect ke object Outfit
        this.dispose();
    }//GEN-LAST:event_pn_btnOutfitMouseClicked

    private void pn_btnPenyewaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnPenyewaanMouseClicked
        new Penyewaan().setVisible(true); //Meredirect ke object Penyewaan
        this.dispose();
    }//GEN-LAST:event_pn_btnPenyewaanMouseClicked

    private void pn_btnPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnPelangganMouseClicked
        new Pelanggan().setVisible(true); //Meredirect ke object Pelanggan
        this.dispose();
    }//GEN-LAST:event_pn_btnPelangganMouseClicked

    private void pn_btnPembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_btnPembayaranMouseClicked
        new Pembayaran().setVisible(true); //Meredirect ke object Pembayaran
        this.dispose();
    }//GEN-LAST:event_pn_btnPembayaranMouseClicked

    private void pn_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_userMouseClicked
        new Pengguna().setVisible(true); //Meredirect ke object Pengguna
        this.dispose();
    }//GEN-LAST:event_pn_userMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked
    
    
    public void CountStatOutfitType(){
        try {
            //2. Query untuk menampilkan data
            //SELECT * FROM nama_tabel
            String statOutfit = "SELECT COUNT(id) FROM outfit";
            
            //3. Koneksi MYSQL
            Connection penghubung = (Connection)koneksiDB.konfigurasi_koneksiDB();
            
            //4. Statement Query
            Statement statement_sql = penghubung.createStatement();
            
            // 5. Eksekusi Query
            ResultSet outfitStat = statement_sql.executeQuery(statOutfit);

            // 6. Ekstraksi nilai dari ResultSet
            StringBuilder outfitResultStringBuilder = new StringBuilder();
            while (outfitStat.next()) {
                int outfitCount = outfitStat.getInt(1); // Mengambil nilai pertama dari setiap baris
                outfitResultStringBuilder.append(outfitCount); // Menggunakan StringBuilder untuk membangun String
            }
            
            // 7. Konversi StringBuilder menjadi String
            String outfitResult = outfitResultStringBuilder.toString();

            // 8. Pemberian Variabel pada label
            StatKostumNumber.setText(outfitResult);

        } catch (Exception e) {
            //7. Tampilkan kesalahan / bug
            e.printStackTrace();
        }
        
    };
    
    public void CountStatOutfitQTY(){
        try {
            //2. Query untuk menampilkan data
            //SELECT * FROM nama_tabel
            String jumlahOutfit = "SELECT SUM(jumlah) FROM outfit";
            
            //3. Koneksi MYSQL
            Connection penghubung = (Connection)koneksiDB.konfigurasi_koneksiDB();
            
            //4. Statement Query
            Statement statement_sql = penghubung.createStatement();
            
            // 5. Eksekusi Query
            ResultSet outfitStat = statement_sql.executeQuery(jumlahOutfit);

            // 6. Ekstraksi nilai dari ResultSet
            StringBuilder outfitResultStringBuilder = new StringBuilder();
            while (outfitStat.next()) {
                int outfitCount = outfitStat.getInt(1); // Mengambil nilai pertama dari setiap baris
                outfitResultStringBuilder.append(outfitCount); // Menggunakan StringBuilder untuk membangun String
            }
            
            // 7. Konversi StringBuilder menjadi String
            String outfitResult = outfitResultStringBuilder.toString();

            // 8. Pemberian Variabel pada label
            StatKostumQTY.setText(outfitResult);

        } catch (Exception e) {
            //7. Tampilkan kesalahan / bug
            e.printStackTrace();
        }
        
    };
    
    public void CountStatRented(){
        try {
            //2. Query untuk menampilkan data
            //SELECT * FROM nama_tabel
            String statPinjam = "SELECT COUNT(idPenyewaan) FROM penyewaan";
            
            //3. Koneksi MYSQL
            Connection penghubung = (Connection)koneksiDB.konfigurasi_koneksiDB();
            
            //4. Statement Query
            Statement statement_sql = penghubung.createStatement();
            
            // 5. Eksekusi Query
            ResultSet pinjamStat = statement_sql.executeQuery(statPinjam);

            // 6. Ekstraksi nilai dari ResultSet
            
            StringBuilder pinjamResultStringBuilder = new StringBuilder();
            while (pinjamStat.next()) {
                int pinjamCount = pinjamStat.getInt(1); // Mengambil nilai pertama dari setiap baris
                pinjamResultStringBuilder.append(pinjamCount); // Menggunakan StringBuilder untuk membangun String
            }
            
            
            // 7. Konversi StringBuilder menjadi String
            String pinjamResult = pinjamResultStringBuilder.toString();

            // 8. Pemberian Variabel pada label
            KostumDipinjam.setText(pinjamResult);

        } catch (Exception e) {
            //7. Tampilkan kesalahan / bug
            e.printStackTrace();
        }
        
    };
    
    public void CountStatAvailable(){
        try {
            //2. Query untuk menampilkan data
            //SELECT * FROM nama_tabel
            String statTersedia = "SELECT (SUM(o.jumlah) - COUNT(p.idPenyewaan))" +
                                "FROM outfit o LEFT JOIN penyewaan p ON o.id = p.idPakaianCosplay";
            
            //3. Koneksi MYSQL
            Connection penghubung = (Connection)koneksiDB.konfigurasi_koneksiDB();
            
            //4. Statement Query
            Statement statement_sql = penghubung.createStatement();
            
            // 5. Eksekusi Query
            ResultSet tersediaStat = statement_sql.executeQuery(statTersedia);

            // 6. Ekstraksi nilai dari ResultSet
            
            StringBuilder AvailableResultStringBuilder = new StringBuilder();
            while (tersediaStat.next()) {
                int AvailableCount = tersediaStat.getInt(1); // Mengambil nilai pertama dari setiap baris
                AvailableResultStringBuilder.append(AvailableCount); // Menggunakan StringBuilder untuk membangun String
            }
            
            
            // 7. Konversi StringBuilder menjadi String
            String AvailableResult = AvailableResultStringBuilder.toString();

            // 8. Pemberian Variabel pada label
            StatAvailable.setText(AvailableResult);

        } catch (Exception e) {
            //7. Tampilkan kesalahan / bug
            e.printStackTrace();
        }
        
    };
    
    public void CountRevenue(){
        try {
            //2. Query untuk menampilkan data
            //SELECT * FROM nama_tabel
            String pendapatan = "SELECT SUM(jumlahBayar) FROM pembayaran";
            
            //3. Koneksi MYSQL
            Connection penghubung = (Connection)koneksiDB.konfigurasi_koneksiDB();
            
            //4. Statement Query
            Statement statement_sql = penghubung.createStatement();
            
            // 5. Eksekusi Query
            ResultSet totalPemasukan = statement_sql.executeQuery(pendapatan);

            // 6. Ekstraksi nilai dari ResultSet
            
            StringBuilder revenueResultStringBuilder = new StringBuilder();
            while (totalPemasukan.next()) {
                int revenue = totalPemasukan.getInt(1); // Mengambil nilai pertama dari setiap baris
                revenueResultStringBuilder.append("Rp. ").append(revenue); // Menggunakan StringBuilder untuk membangun String
            }
            
            
            // 7. Konversi StringBuilder menjadi String
            String revenueResult = revenueResultStringBuilder.toString();

            // 8. Pemberian Variabel pada label
            TotalPendapatan.setText(revenueResult);

        } catch (Exception e) {
            //7. Tampilkan kesalahan / bug
            e.printStackTrace();
        }
        
    };
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Catchphrase;
    private javax.swing.JLabel Catchphrase2;
    private javax.swing.JLabel Catchphrase3;
    private javax.swing.JLabel Ikon;
    private javax.swing.JLabel KostumDipinjam;
    private javax.swing.JLabel LabelKostumQTY;
    private javax.swing.JLabel LabelKostumTersedia;
    private javax.swing.JLabel LabelPendapatan;
    private javax.swing.JLabel LabelStatKostum2;
    private javax.swing.JLabel LabelStatKostumType;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel StatAvailable;
    private javax.swing.JPanel StatJumlahKostum;
    private javax.swing.JPanel StatKostum;
    private javax.swing.JPanel StatKostumDipinjam;
    private javax.swing.JLabel StatKostumNumber;
    private javax.swing.JLabel StatKostumQTY;
    private javax.swing.JPanel StatKostumTersedia;
    private javax.swing.JPanel StatTotalPendapatan;
    private javax.swing.JLabel TotalPendapatan;
    private javax.swing.JLabel dash_user;
    private javax.swing.JLabel dash_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel pn_body;
    private javax.swing.JPanel pn_btnDashboard;
    private javax.swing.JPanel pn_btnOutfit;
    private javax.swing.JPanel pn_btnPelanggan;
    private javax.swing.JPanel pn_btnPembayaran;
    private javax.swing.JPanel pn_btnPenyewaan;
    private javax.swing.JPanel pn_line;
    private javax.swing.JPanel pn_line1;
    private javax.swing.JPanel pn_line2;
    private javax.swing.JPanel pn_line3;
    private javax.swing.JPanel pn_line4;
    private javax.swing.JPanel pn_logo;
    private javax.swing.JPanel pn_sidebar;
    private javax.swing.JPanel pn_user;
    // End of variables declaration//GEN-END:variables
}
