/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autentikasi;

import com.mycompany.FantasyFittings.koneksiDB;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafly Ivan Khalfani
 */
public class LupaPW extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public LupaPW() {
        initComponents();
        Image icon = new ImageIcon(getClass().getResource("/images/logo-2.1.png")).getImage();
        setIconImage(icon);
        setTitle("Fantasy Fittings - Forgot Password");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TombolRenew = new javax.swing.JToggleButton();
        Username = new javax.swing.JTextField();
        PasswordB = new javax.swing.JPasswordField();
        KPasswordB = new javax.swing.JPasswordField();
        LabelUsername = new javax.swing.JLabel();
        LabelPassword = new javax.swing.JLabel();
        LabelKonfirmasiPassword = new javax.swing.JLabel();
        PesanLogin = new javax.swing.JLabel();
        TombolLogin = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        TombolRenew.setBackground(new java.awt.Color(0, 153, 255));
        TombolRenew.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TombolRenew.setForeground(new java.awt.Color(255, 255, 255));
        TombolRenew.setText("Renew");
        TombolRenew.setHideActionText(true);
        TombolRenew.setOpaque(true);
        TombolRenew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TombolRenewActionPerformed(evt);
            }
        });

        LabelUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelUsername.setText("User");

        LabelPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelPassword.setText("Password Baru");

        LabelKonfirmasiPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelKonfirmasiPassword.setText("Konfirmasi Password");

        PesanLogin.setText("Sudah punya akun?");

        TombolLogin.setForeground(new java.awt.Color(0, 102, 204));
        TombolLogin.setText("Login");
        TombolLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TombolLoginMouseClicked(evt);
            }
        });

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setText("Lupa Password?");

        BackGround.setBackground(new java.awt.Color(0, 0, 0));
        BackGround.setForeground(new java.awt.Color(255, 255, 255));
        BackGround.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo-name-2.png"))); // NOI18N
        BackGround.setOpaque(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelUsername)
                            .addComponent(Username, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(LabelPassword)
                            .addComponent(PasswordB, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(LabelKonfirmasiPassword)
                            .addComponent(KPasswordB, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(TombolRenew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(PesanLogin)
                        .addGap(7, 7, 7)
                        .addComponent(TombolLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(Title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(33, Short.MAX_VALUE)
                        .addComponent(Title)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(LabelUsername)
                .addGap(4, 4, 4)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(LabelPassword)
                .addGap(4, 4, 4)
                .addComponent(PasswordB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(LabelKonfirmasiPassword)
                .addGap(4, 4, 4)
                .addComponent(KPasswordB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(TombolRenew, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PesanLogin)
                    .addComponent(TombolLogin))
                .addGap(49, 49, 49))
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void clearForm() {
        Username.setText("");
        PasswordB.setText("");
        KPasswordB.setText("");
    }
    
    private void TombolRenewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TombolRenewActionPerformed
        try {
            // Tangkap variabel inputan 
            String uname = Username.getText();
            String pw = new String(PasswordB.getPassword());
            String kpw = new String(KPasswordB.getPassword());

            // Konfirmasi Inputan
            if (!pw.equals(kpw)) {
                JOptionPane.showMessageDialog(null, "Pastikan konfirmasi password sesuai");
                return;
            }

            // Query SQL - INSERT
            String perintahUpdate_SQL = "UPDATE pengguna SET password = ? WHERE username = ?";

            // Menghubungkan SQL - Java
            Connection penghubung = koneksiDB.konfigurasi_koneksiDB();
            if (penghubung == null) {
                JOptionPane.showMessageDialog(null, "Koneksi ke database gagal. Silakan cek konfigurasi database Anda.");
                return;
            }

            // Menggunakan transaction untuk validasi data
            penghubung.setAutoCommit(false); // Start transaction

            try {
                // Buat PreparedStatement
                PreparedStatement pernyataanSQL = penghubung.prepareStatement(perintahUpdate_SQL);
                pernyataanSQL.setString(1, pw);
                pernyataanSQL.setString(2, uname);

                // Eksekusi perintah SQL
                int rowsUpdated = pernyataanSQL.executeUpdate();

                // Validasi data SQL
                if (rowsUpdated > 0) {
                    // Commit transaction
                    penghubung.commit();

                    // Success condition
                    JOptionPane.showMessageDialog(null, "Pembaruan Password Berhasil.");
                    new Login().setVisible(true); // Redirect to Login object
                    this.dispose(); // Close current window
                } else {
                    // Failure condition
                    JOptionPane.showMessageDialog(null, "Gagal Memperbarui Password.");
                    clearForm();
                }

                // Close pernyataanSQL
                pernyataanSQL.close();
            } catch (SQLException e) {
                // Rollback transaction saat terjadi error
                penghubung.rollback();
                JOptionPane.showMessageDialog(null, "Gagal Memperbarui Password \n" + e.getMessage());
            } finally {
                // Mengembalikan auto-commit ke mode on dan close connection
                penghubung.setAutoCommit(true);
                penghubung.close();
            }

        } catch (SQLException e) {
            // 07. Exception()
            JOptionPane.showMessageDialog(null, "Registrasi Gagal \n" + e.getMessage());
        }
    }//GEN-LAST:event_TombolRenewActionPerformed

    private void TombolLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TombolLoginMouseClicked
        new Login().setVisible(true); //Meredirect ke object Register
        this.dispose();
    }//GEN-LAST:event_TombolLoginMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LupaPW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LupaPW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LupaPW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LupaPW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LupaPW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JPasswordField KPasswordB;
    private javax.swing.JLabel LabelKonfirmasiPassword;
    private javax.swing.JLabel LabelPassword;
    private javax.swing.JLabel LabelUsername;
    private javax.swing.JPasswordField PasswordB;
    private javax.swing.JLabel PesanLogin;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel TombolLogin;
    private javax.swing.JToggleButton TombolRenew;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
